### ISSUE TITLE
Project still relevant?

### ISSUE THREAD

**Issue by dandv** [double-commander/doublecmd#33]
The README states,

> The goal of this fork is to relief this project from the constraints of archaic development methotodloies by facilitating github capabilities to achieve a better collaboration and attract developers to improve this software to be the best it can.

https://github.com/doublecmd/doublecmd is very actively maintained, with over 10,000 commits now.

Is this fork still necessary?

If not, please consider [archiving the repo](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories), so it doesn't show up more prominently in Google searches than the original project.

**Comment by TheNicker** [comment]
Is this repository overshadows the official one in search engines ?

Google should always display the official project first so I don't see how this one would interfere with everyday work, as I presume this was the trigger for opening the issue.

There is sense in your claim . The official Double commander project has been improved in terms of collaboration and transparency since this repository has been created, and since the official project has been moving forward, it appears that it makes this one somewhat obsolete.

This fork created due to different opinions about development methodologies and this disparity probably exists till this day.
Yes, the official project is now in github and that's closing the gap.

As you claim, this repository achieved its main goal, but there are secondary goals derived from the above.
e.g. there are several changes that were made here on top of the official project that probably won't get integrated as is, moreover it leaves room for potential changes that also are not viable for integration.

Concluding the above:

The official goal of this repository should be changed.
It seems that there's no effective conflict with the search engines (please correct me if I'm wrong).
At this moment I'm not convinced that this repository should be closed/archived and I believe it should be open for people who sees this project from another angle.

**Comment by dandv** [comment]
Thanks for the explanation. The way I discovered this project was by searching for something like "cross platform file manager github", which for me had returned this project in the first page of results (the original one wasn't there).

Maybe the README can be updated with a more prominent indication of the nature and purpose of the fork. Right now it starts in an ambiguous way, easy to glide over and consider the original as something worth overlooking:

![image](https://user-images.githubusercontent.com/33569/215215984-3e8baddd-e4d2-465d-b0c2-bb6037c6aef9.png)

There's no link to the upstream even.

A clearer README heading could be,

> This is a fork of Double Commander, which differs in the following ways:
> 1. X
> 2. Y
> 3. Z

**Comment by TheNicker** [comment]
@dandv, thanks for bringing this matter forward

I agree that Readme should be updated.

The official repo should get more credit and encouraged to be redirected to. 
This repo should be presented more clearly as a fork.
The goal should be removed since it's not true and misleads.

b.t.w
There is' a link to the upstream , it's the second link in the page

**Comment by goyalyashpal** [comment]
oh my god wait a second.. i am on unofficial repo 🤦 - aah

**Comment by Neustradamus** [comment]
To follow
